version: '3.8'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://mongo:27017/online-code-editor
      - REDIS_URL=redis://redis:6379
    ports:
      - "5001:5002"
    depends_on:
      - mongo
      - redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp

  mongo:
    image: mongo:6.0
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data: